#!/bin/bash
# MoAI Statusline Wrapper - Generated by moai-adk
# This script forwards stdin JSON to the moai statusline command.
# Paths are configured during project initialization.

# Create temp file to store stdin
temp_file=$(mktemp)
trap 'rm -f "$temp_file"' EXIT

# Read stdin into temp file
cat > "$temp_file"

# Try moai command in PATH first
if command -v moai &> /dev/null; then
	exec moai statusline < "$temp_file"
fi

# Fall back to well-known install locations, relative to the current $HOME.
# Both bare and .exe names are probed so the same script works on
# macOS/Linux and on Windows (Git Bash).
for candidate in \
	"$HOME/go/bin/moai" \
	"$HOME/go/bin/moai.exe" \
	"$HOME/.local/bin/moai" \
	"$HOME/.local/bin/moai.exe"
do
	if [ -f "$candidate" ]; then
		exec "$candidate" statusline < "$temp_file"
	fi
done

# Not found - exit silently (Claude Code handles missing statusline gracefully)
exit 0
